<?php
/**
* Generated by the WordPress Option Page generator
* at http://jeremyhixon.com/wp-tools/option-page/
*/

class ESports {
private $esports_options;

public function __construct() {
add_action( 'admin_menu', array( $this, 'esports_add_plugin_page' ) );
add_action( 'admin_init', array( $this, 'esports_page_init' ) );
}

public function esports_add_plugin_page() {
add_menu_page(
'eSports', // page_title
'eSports', // menu_title
'manage_options', // capability
'esports', // menu_slug
array( $this, 'esports_create_admin_page' ), // function
'dashicons-admin-tools', // icon_url
3 // position
);
}

public function esports_create_admin_page() {
$this->esports_options = get_option( 'esports_option_name' ); ?>

<div class="wrap">
    <h2>eSports</h2>
    <p>eSports tools</p>
    <?php settings_errors(); ?>

    <form method="post" action="options.php">
        <?php
					settings_fields( 'esports_option_group' );
					do_settings_sections( 'esports-admin' );
					submit_button();
				?>
    </form>
</div>
<?php }

	public function esports_page_init() {
		register_setting(
			'esports_option_group', // option_group
			'esports_option_name', // option_name
			array( $this, 'esports_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'esports_setting_section', // id
			'Settings', // title
			array( $this, 'esports_section_info' ), // callback
			'esports-admin' // page
		);

		add_settings_field(
			'delete_all_options_with_plugin_0', // id
			'Delete all options with plugin', // title
			array( $this, 'delete_all_options_with_plugin_0_callback' ), // callback
			'esports-admin', // page
			'esports_setting_section' // section
		);
	}

	public function esports_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['delete_all_options_with_plugin_0'] ) ) {
			$sanitary_values['delete_all_options_with_plugin_0'] = $input['delete_all_options_with_plugin_0'];
		}

		return $sanitary_values;
	}

	public function esports_section_info() {
		
	}

	public function delete_all_options_with_plugin_0_callback() {
		printf(
			'<input type="checkbox" name="esports_option_name[delete_all_options_with_plugin_0]" id="delete_all_options_with_plugin_0" value="delete_all_options_with_plugin_0" %s>',
			( isset( $this->esports_options['delete_all_options_with_plugin_0'] ) && $this->esports_options['delete_all_options_with_plugin_0'] === 'delete_all_options_with_plugin_0' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$esports = new ESports();

/* 
 * Retrieve this value with:
 * $esports_options = get_option( 'esports_option_name' ); // Array of All Options
 * $delete_all_options_with_plugin_0 = $esports_options['delete_all_options_with_plugin_0']; // Delete all options with plugin
 */